### ISSUE TITLE
Tag 0.0.4 mismatch master content

### ISSUE THREAD

**Issue by Akaryatrh** [ngryman/grunt-glue-js#4]
Hey,
  
It seems that the tag branch `0.0.4` is not the same as the `master` branch.
So for now i can't add it to my `package.json` file this way
```json
"dependencies": {
	"grunt-glue-js": "0.0.x"
}
```

And i have to require it that way
```json
"dependencies": {
	"grunt-glue-js": "ngryman/grunt-glue-js#master",
}
```

This is not really handy if i want to stick to a minor version of your lib :)

**Comment by ngryman** [comment]
Hey,

I just made a new release: `0.0.5`.
